### ISSUE TITLE
video demo no signal

### ISSUE THREAD

**Issue by LeiiY** [siqueira-hc/Efficient-Facial-Feature-Learning-with-Wide-Ensemble-based-Convolutional-Neural-Networks#3] opened 2020-03-24 10:19 UTC
hi，i run the video from AFF-Wild trainning set（216.mp4  133.avi）, but ended with no signal,my os is Ubuntu18.04.
![8LnQL8.png](https://s1.ax1x.com/2020/03/24/8LnQL8.png)

**Comment by siqueira-hc** [comment] 2020-03-24 11:31
Dear LeiiY,

Could you, please, send me the error message shown in your terminal (behind the "No Signal" Window)?

Is this screen shown after processing the video clip?

In the positive case, the framework shows "No Signal" when there are no further frames for processing. You can press "Esc" or close the window to quit the demonstration.

If you are running the framework on all the data from AFF-Wild, you can call cv2.destroyWindow(""Siqueira_et_al_AAAI_2020") or cv2.destroyAllWindows() in your python script to close the "No Signal" window.

I will change the text. It is not intuitive.

Thank you for your interest and your message.

Best,
Henrique Siqueira

P.S. Please, let me know if the problem is solved.

**Comment by LeiiY** [comment] 2020-03-24 11:47
yeah,no further frames,but i added the argument `-o  ./media/output.csv`,after processing ,close the windows or press esc, the file output.csv did not generate,why?
![8LdeHJ.png](https://s1.ax1x.com/2020/03/24/8LdeHJ.png)

**Comment by siqueira-hc** [comment] 2020-03-24 11:57
Dear LeiiY,

It is because this feature is on development as you can see in the GitHub page: [https://github.com/siqueira-hc/Efficient-Facial-Feature-Learning-with-Wide-Ensemble-based-Convolutional-Neural-Networks#list-of-arguments](https://github.com/siqueira-hc/Efficient-Facial-Feature-Learning-with-Wide-Ensemble-based-Convolutional-Neural-Networks#list-of-arguments)

![Screenshot](https://user-images.githubusercontent.com/26622989/77423073-d2a2fc80-6d8b-11ea-91f6-89e6a04ffa65.PNG)

Since you are interested in this feature I will prioritize its development.

I will close this issue as there is no error and open another issue regarding the development of the new feature.

I plan to add the new feature until the end of this week.

Best wishes,
Henrique Siqueira

**Closed by siqueira-hc** 2020-03-24 11:57 UTC

**Comment by siqueira-hc** [comment] 2020-04-01 11:09
Dear LeiiY,

You can now save predictions to a CSV file!

Best,
Henrique Siqueira
